/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dharma.model.impl;

import com.dharma.model.PMDeletedMessage;
import com.dharma.model.PMDeletedMessageModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PMDeletedMessage service. Represents a row in the &quot;deleted_message&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.dharma.model.PMDeletedMessageModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PMDeletedMessageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PMDeletedMessageImpl
 * @see com.dharma.model.PMDeletedMessage
 * @see com.dharma.model.PMDeletedMessageModel
 * @generated
 */
public class PMDeletedMessageModelImpl extends BaseModelImpl<PMDeletedMessage>
	implements PMDeletedMessageModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a p m deleted message model instance should use the {@link com.dharma.model.PMDeletedMessage} interface instead.
	 */
	public static final String TABLE_NAME = "deleted_message";
	public static final Object[][] TABLE_COLUMNS = {
			{ "deletedMessageId", Types.BIGINT },
			{ "messageId", Types.BIGINT },
			{ "ownerId", Types.BIGINT },
			{ "deletedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table deleted_message (deletedMessageId LONG not null primary key,messageId LONG,ownerId LONG,deletedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table deleted_message";
	public static final String ORDER_BY_JPQL = " ORDER BY pmDeletedMessage.deletedDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY deleted_message.deletedDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.dharma.model.PMDeletedMessage"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.dharma.model.PMDeletedMessage"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.dharma.model.PMDeletedMessage"),
			true);
	public static long MESSAGEID_COLUMN_BITMASK = 1L;
	public static long OWNERID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.dharma.model.PMDeletedMessage"));

	public PMDeletedMessageModelImpl() {
	}

	public long getPrimaryKey() {
		return _deletedMessageId;
	}

	public void setPrimaryKey(long primaryKey) {
		setDeletedMessageId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_deletedMessageId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return PMDeletedMessage.class;
	}

	public String getModelClassName() {
		return PMDeletedMessage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("deletedMessageId", getDeletedMessageId());
		attributes.put("messageId", getMessageId());
		attributes.put("ownerId", getOwnerId());
		attributes.put("deletedDate", getDeletedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long deletedMessageId = (Long)attributes.get("deletedMessageId");

		if (deletedMessageId != null) {
			setDeletedMessageId(deletedMessageId);
		}

		Long messageId = (Long)attributes.get("messageId");

		if (messageId != null) {
			setMessageId(messageId);
		}

		Long ownerId = (Long)attributes.get("ownerId");

		if (ownerId != null) {
			setOwnerId(ownerId);
		}

		Date deletedDate = (Date)attributes.get("deletedDate");

		if (deletedDate != null) {
			setDeletedDate(deletedDate);
		}
	}

	public long getDeletedMessageId() {
		return _deletedMessageId;
	}

	public void setDeletedMessageId(long deletedMessageId) {
		_deletedMessageId = deletedMessageId;
	}

	public long getMessageId() {
		return _messageId;
	}

	public void setMessageId(long messageId) {
		_columnBitmask |= MESSAGEID_COLUMN_BITMASK;

		if (!_setOriginalMessageId) {
			_setOriginalMessageId = true;

			_originalMessageId = _messageId;
		}

		_messageId = messageId;
	}

	public long getOriginalMessageId() {
		return _originalMessageId;
	}

	public long getOwnerId() {
		return _ownerId;
	}

	public void setOwnerId(long ownerId) {
		_columnBitmask |= OWNERID_COLUMN_BITMASK;

		if (!_setOriginalOwnerId) {
			_setOriginalOwnerId = true;

			_originalOwnerId = _ownerId;
		}

		_ownerId = ownerId;
	}

	public long getOriginalOwnerId() {
		return _originalOwnerId;
	}

	public Date getDeletedDate() {
		return _deletedDate;
	}

	public void setDeletedDate(Date deletedDate) {
		_columnBitmask = -1L;

		_deletedDate = deletedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			PMDeletedMessage.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PMDeletedMessage toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (PMDeletedMessage)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		PMDeletedMessageImpl pmDeletedMessageImpl = new PMDeletedMessageImpl();

		pmDeletedMessageImpl.setDeletedMessageId(getDeletedMessageId());
		pmDeletedMessageImpl.setMessageId(getMessageId());
		pmDeletedMessageImpl.setOwnerId(getOwnerId());
		pmDeletedMessageImpl.setDeletedDate(getDeletedDate());

		pmDeletedMessageImpl.resetOriginalValues();

		return pmDeletedMessageImpl;
	}

	public int compareTo(PMDeletedMessage pmDeletedMessage) {
		int value = 0;

		value = DateUtil.compareTo(getDeletedDate(),
				pmDeletedMessage.getDeletedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		PMDeletedMessage pmDeletedMessage = null;

		try {
			pmDeletedMessage = (PMDeletedMessage)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = pmDeletedMessage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		PMDeletedMessageModelImpl pmDeletedMessageModelImpl = this;

		pmDeletedMessageModelImpl._originalMessageId = pmDeletedMessageModelImpl._messageId;

		pmDeletedMessageModelImpl._setOriginalMessageId = false;

		pmDeletedMessageModelImpl._originalOwnerId = pmDeletedMessageModelImpl._ownerId;

		pmDeletedMessageModelImpl._setOriginalOwnerId = false;

		pmDeletedMessageModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PMDeletedMessage> toCacheModel() {
		PMDeletedMessageCacheModel pmDeletedMessageCacheModel = new PMDeletedMessageCacheModel();

		pmDeletedMessageCacheModel.deletedMessageId = getDeletedMessageId();

		pmDeletedMessageCacheModel.messageId = getMessageId();

		pmDeletedMessageCacheModel.ownerId = getOwnerId();

		Date deletedDate = getDeletedDate();

		if (deletedDate != null) {
			pmDeletedMessageCacheModel.deletedDate = deletedDate.getTime();
		}
		else {
			pmDeletedMessageCacheModel.deletedDate = Long.MIN_VALUE;
		}

		return pmDeletedMessageCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{deletedMessageId=");
		sb.append(getDeletedMessageId());
		sb.append(", messageId=");
		sb.append(getMessageId());
		sb.append(", ownerId=");
		sb.append(getOwnerId());
		sb.append(", deletedDate=");
		sb.append(getDeletedDate());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.dharma.model.PMDeletedMessage");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>deletedMessageId</column-name><column-value><![CDATA[");
		sb.append(getDeletedMessageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>messageId</column-name><column-value><![CDATA[");
		sb.append(getMessageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ownerId</column-name><column-value><![CDATA[");
		sb.append(getOwnerId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deletedDate</column-name><column-value><![CDATA[");
		sb.append(getDeletedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PMDeletedMessage.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			PMDeletedMessage.class
		};
	private long _deletedMessageId;
	private long _messageId;
	private long _originalMessageId;
	private boolean _setOriginalMessageId;
	private long _ownerId;
	private long _originalOwnerId;
	private boolean _setOriginalOwnerId;
	private Date _deletedDate;
	private long _columnBitmask;
	private PMDeletedMessage _escapedModelProxy;
}