/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dharma.model.impl;

import com.dharma.model.PMReadMessage;
import com.dharma.model.PMReadMessageModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PMReadMessage service. Represents a row in the &quot;read_message&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.dharma.model.PMReadMessageModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PMReadMessageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PMReadMessageImpl
 * @see com.dharma.model.PMReadMessage
 * @see com.dharma.model.PMReadMessageModel
 * @generated
 */
public class PMReadMessageModelImpl extends BaseModelImpl<PMReadMessage>
	implements PMReadMessageModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a p m read message model instance should use the {@link com.dharma.model.PMReadMessage} interface instead.
	 */
	public static final String TABLE_NAME = "read_message";
	public static final Object[][] TABLE_COLUMNS = {
			{ "readMessageId", Types.BIGINT },
			{ "messageId", Types.BIGINT },
			{ "readDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table read_message (readMessageId LONG not null primary key,messageId LONG,readDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table read_message";
	public static final String ORDER_BY_JPQL = " ORDER BY pmReadMessage.readDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY read_message.readDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.dharma.model.PMReadMessage"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.dharma.model.PMReadMessage"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.dharma.model.PMReadMessage"),
			true);
	public static long MESSAGEID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.dharma.model.PMReadMessage"));

	public PMReadMessageModelImpl() {
	}

	public long getPrimaryKey() {
		return _readMessageId;
	}

	public void setPrimaryKey(long primaryKey) {
		setReadMessageId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_readMessageId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return PMReadMessage.class;
	}

	public String getModelClassName() {
		return PMReadMessage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("readMessageId", getReadMessageId());
		attributes.put("messageId", getMessageId());
		attributes.put("readDate", getReadDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long readMessageId = (Long)attributes.get("readMessageId");

		if (readMessageId != null) {
			setReadMessageId(readMessageId);
		}

		Long messageId = (Long)attributes.get("messageId");

		if (messageId != null) {
			setMessageId(messageId);
		}

		Date readDate = (Date)attributes.get("readDate");

		if (readDate != null) {
			setReadDate(readDate);
		}
	}

	public long getReadMessageId() {
		return _readMessageId;
	}

	public void setReadMessageId(long readMessageId) {
		_readMessageId = readMessageId;
	}

	public long getMessageId() {
		return _messageId;
	}

	public void setMessageId(long messageId) {
		_columnBitmask |= MESSAGEID_COLUMN_BITMASK;

		if (!_setOriginalMessageId) {
			_setOriginalMessageId = true;

			_originalMessageId = _messageId;
		}

		_messageId = messageId;
	}

	public long getOriginalMessageId() {
		return _originalMessageId;
	}

	public Date getReadDate() {
		return _readDate;
	}

	public void setReadDate(Date readDate) {
		_columnBitmask = -1L;

		_readDate = readDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			PMReadMessage.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PMReadMessage toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (PMReadMessage)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		PMReadMessageImpl pmReadMessageImpl = new PMReadMessageImpl();

		pmReadMessageImpl.setReadMessageId(getReadMessageId());
		pmReadMessageImpl.setMessageId(getMessageId());
		pmReadMessageImpl.setReadDate(getReadDate());

		pmReadMessageImpl.resetOriginalValues();

		return pmReadMessageImpl;
	}

	public int compareTo(PMReadMessage pmReadMessage) {
		int value = 0;

		value = DateUtil.compareTo(getReadDate(), pmReadMessage.getReadDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		PMReadMessage pmReadMessage = null;

		try {
			pmReadMessage = (PMReadMessage)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = pmReadMessage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		PMReadMessageModelImpl pmReadMessageModelImpl = this;

		pmReadMessageModelImpl._originalMessageId = pmReadMessageModelImpl._messageId;

		pmReadMessageModelImpl._setOriginalMessageId = false;

		pmReadMessageModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PMReadMessage> toCacheModel() {
		PMReadMessageCacheModel pmReadMessageCacheModel = new PMReadMessageCacheModel();

		pmReadMessageCacheModel.readMessageId = getReadMessageId();

		pmReadMessageCacheModel.messageId = getMessageId();

		Date readDate = getReadDate();

		if (readDate != null) {
			pmReadMessageCacheModel.readDate = readDate.getTime();
		}
		else {
			pmReadMessageCacheModel.readDate = Long.MIN_VALUE;
		}

		return pmReadMessageCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{readMessageId=");
		sb.append(getReadMessageId());
		sb.append(", messageId=");
		sb.append(getMessageId());
		sb.append(", readDate=");
		sb.append(getReadDate());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.dharma.model.PMReadMessage");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>readMessageId</column-name><column-value><![CDATA[");
		sb.append(getReadMessageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>messageId</column-name><column-value><![CDATA[");
		sb.append(getMessageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>readDate</column-name><column-value><![CDATA[");
		sb.append(getReadDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PMReadMessage.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			PMReadMessage.class
		};
	private long _readMessageId;
	private long _messageId;
	private long _originalMessageId;
	private boolean _setOriginalMessageId;
	private Date _readDate;
	private long _columnBitmask;
	private PMReadMessage _escapedModelProxy;
}